export default [
    { id: 0, label: "--" },
    { id: 1, label: "Mario Kart Stadium" },
    { id: 2, label: "Water Park" },
    { id: 3, label: "Sweet Sweet Canyon" },
    { id: 4, label: "Thwomp Ruins" },
    { id: 5, label: "Mario Circuit" },
    { id: 6, label: "Toad Harbour" },
    { id: 7, label: "Twisted Mansion" },
    { id: 8, label: "Shy Guy Falls" },
    { id: 9, label: "Sunshine Airport" },
    { id: 10, label: "Dolphin Shoals" },
    { id: 11, label: "Electrodrome" },
    { id: 12, label: "Mount Wario" },
    { id: 13, label: "Cloudtop Cruise" },
    { id: 14, label: "Bone Dry Dunes" },
    { id: 15, label: "Bowser's Castle" },
    { id: 16, label: "Rainbow Road" },
    { id: 17, label: "Moo Moo Meadows (Wii)" },
    { id: 18, label: "Mario Circuit (GBA)" },
    { id: 19, label: "Cheep Cheep Beach (DS)" },
    { id: 20, label: "Toad’s Turnpike (N64)" },
    { id: 21, label: "Dry Dry Desert (GCN)" },
    { id: 22, label: "Donut Plains 3 (SNES)" },
    { id: 23, label: "Royal Raceway (N64)" },
    { id: 24, label: "DK Jungle (3DS)" },
    { id: 25, label: "Wario Stadium (DS)" },
    { id: 26, label: "Sherbet Land (GCN)" },
    { id: 27, label: "Music Park (3DS)" },
    { id: 28, label: "Yoshi Valley (N64)" },
    { id: 29, label: "Tick-Tock Clock (DS)" },
    { id: 30, label: "Piranhna Plant Slide (3DS)" },
    { id: 31, label: "Grumble Volcano (Wii)" },
    { id: 32, label: "Rainbow Road (N64)" },
    { id: 33, label: "Yoshi Circuit (GCN)" },
    { id: 34, label: "Excitebike Arena" },
    { id: 35, label: "Dragon Driftway" },
    { id: 36, label: "Mute City" },
    { id: 37, label: "Wario's Goldmine (Wii)" },
    { id: 38, label: "Rainbow Road (SNES)" },
    { id: 39, label: "Ice Ice Outpost" },
    { id: 40, label: "Hyrule Circuit" },
    { id: 41, label: "Baby Park (GCN)" },
    { id: 42, label: "Cheese Land (GBA)" },
    { id: 43, label: "Wild Woods" },
    { id: 44, label: "Animal Crossing" },
    { id: 45, label: "Neo Bowser City (3DS)" },
    { id: 46, label: "Ribbon Road" },
    { id: 47, label: "Super Bell Subway" },
    { id: 48, label: "Big Blue" }
];
